siteName: Hotel Paradis
tagline: Sit back, relax and enjoy
mewsConfigId: 4808678c-b67e-44bf-ad85-ae2800f64c7f
gtmContainerId: GTM-MMGRQ6DS
ga4MeasurementId: G-P3MPE9WLYQ
email: reservations@hotelparadis.example
phone: +31 20 000 0000
address: |-
  Paradijsweg 2
  2042 GC Zandvoort
  Netherlands
social: {}
